import type { Metadata } from "next";

import "./globals.css";
import QueryProvider from "@/app/hook/__provider";
import SessionWrapper from "./SessionWrapper";
import Informations from "@/components/SectionDown/Informations";
import HelpSection from "@/components/SectionDown/HelpSection";
import Newsletter from "@/components/SectionDown/Newsletter";
import Footer from "@/components/SectionDown/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={` antialiased`}>
          <QueryProvider>{children}</QueryProvider>
          <Informations />
          <Newsletter />
          <HelpSection />
          <div className="container mx-auto">
            <Footer />
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
