import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/app/hook/__provider";
import SessionWrapper from "./SessionWrapper";
import Informations from "@/components/BottomSection/Informations";
import HelpSection from "@/components/BottomSection/HelpSection";
import Newsletter from "@/components/BottomSection/Newsletter";
import Footer from "@/components/BottomSection/Footer";
import { NuqsAdapter } from "nuqs/adapters/next/app";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={` antialiased`}>
          <QueryProvider>
            <NuqsAdapter>{children}</NuqsAdapter>
          </QueryProvider>
          <Informations />
          <Newsletter />
          <HelpSection />
          <div className="container mx-auto">
            <Footer />
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
